/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Pretendard',
          '-apple-system',
          'BlinkMacSystemFont',
          'system-ui',
          'Roboto',
          'Helvetica Neue',
          'Segoe UI',
          'Apple SD Gothic Neo',
          'Noto Sans KR',
          'Malgun Gothic',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'sans-serif',
        ],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontSize: {
        // Primitive sizes
        'size-9': ['var(--text-size-9)', { lineHeight: 'var(--text-size-9--line-height)' }],
        'size-10': ['var(--text-size-10)', { lineHeight: 'var(--text-size-10--line-height)' }],
        'size-11': ['var(--text-size-11)', { lineHeight: 'var(--text-size-11--line-height)' }],
        'size-12': ['var(--text-size-12)', { lineHeight: 'var(--text-size-12--line-height)' }],
        'size-13': ['var(--text-size-13)', { lineHeight: 'var(--text-size-13--line-height)' }],
        'size-14': ['var(--text-size-14)', { lineHeight: 'var(--text-size-14--line-height)' }],
        'size-15': ['var(--text-size-15)', { lineHeight: 'var(--text-size-15--line-height)' }],
        'size-16': ['var(--text-size-16)', { lineHeight: 'var(--text-size-16--line-height)' }],
        'size-18': ['var(--text-size-18)', { lineHeight: 'var(--text-size-18--line-height)' }],
        'size-20': ['var(--text-size-20)', { lineHeight: 'var(--text-size-20--line-height)' }],
        'size-22': ['var(--text-size-22)', { lineHeight: 'var(--text-size-22--line-height)' }],
        'size-24': ['var(--text-size-24)', { lineHeight: 'var(--text-size-24--line-height)' }],
        'size-28': ['var(--text-size-28)', { lineHeight: 'var(--text-size-28--line-height)' }],
        'size-32': ['var(--text-size-32)', { lineHeight: 'var(--text-size-32--line-height)' }],

        // Semantic Typography - Page Title (Bold)
        'page-title-1': ['var(--text-size-28)', { lineHeight: 'var(--text-size-28--line-height)', fontWeight: '700' }],
        'page-title-2': ['var(--text-size-24)', { lineHeight: 'var(--text-size-24--line-height)', fontWeight: '700' }],
        'page-title-3': ['var(--text-size-22)', { lineHeight: 'var(--text-size-22--line-height)', fontWeight: '700' }],
        'page-title-4': ['var(--text-size-20)', { lineHeight: 'var(--text-size-20--line-height)', fontWeight: '700' }],

        // Semantic Typography - Headline (Bold)
        'h1': ['var(--text-size-24)', { lineHeight: 'var(--text-size-24--line-height)', fontWeight: '700' }],
        'h2': ['var(--text-size-22)', { lineHeight: 'var(--text-size-22--line-height)', fontWeight: '700' }],
        'h3': ['var(--text-size-20)', { lineHeight: 'var(--text-size-20--line-height)', fontWeight: '700' }],
        'h4': ['var(--text-size-18)', { lineHeight: 'var(--text-size-18--line-height)', fontWeight: '700' }],
        'h5': ['var(--text-size-16)', { lineHeight: 'var(--text-size-16--line-height)', fontWeight: '700' }],

        // Semantic Typography - Title (Semi-Bold)
        'title-1': ['var(--text-size-20)', { lineHeight: 'var(--text-size-20--line-height)', fontWeight: '600' }],
        'title-2': ['var(--text-size-18)', { lineHeight: 'var(--text-size-18--line-height)', fontWeight: '600' }],
        'title-3': ['var(--text-size-16)', { lineHeight: 'var(--text-size-16--line-height)', fontWeight: '600' }],
        'title-4': ['var(--text-size-15)', { lineHeight: 'var(--text-size-15--line-height)', fontWeight: '600' }],

        // Semantic Typography - Label (Bold)
        'label-1': ['var(--text-size-16)', { lineHeight: 'var(--text-size-16--line-height)', fontWeight: '700' }],
        'label-2': ['var(--text-size-15)', { lineHeight: 'var(--text-size-15--line-height)', fontWeight: '700' }],
        'label-3': ['var(--text-size-14)', { lineHeight: 'var(--text-size-14--line-height)', fontWeight: '700' }],
        'label-4': ['var(--text-size-13)', { lineHeight: 'var(--text-size-13--line-height)', fontWeight: '700' }],
        'label-5': ['var(--text-size-12)', { lineHeight: 'var(--text-size-12--line-height)', fontWeight: '700' }],
        'label-6': ['var(--text-size-11)', { lineHeight: 'var(--text-size-11--line-height)', fontWeight: '700' }],

        // Semantic Typography - Body (Regular)
        'body-1': ['var(--text-size-16)', { lineHeight: 'var(--text-size-16--line-height)', fontWeight: '400' }],
        'body-2': ['var(--text-size-15)', { lineHeight: 'var(--text-size-15--line-height)', fontWeight: '400' }],
        'body-3': ['var(--text-size-14)', { lineHeight: 'var(--text-size-14--line-height)', fontWeight: '400' }],
        'body-4': ['var(--text-size-13)', { lineHeight: 'var(--text-size-13--line-height)', fontWeight: '400' }],
        'body-5': ['var(--text-size-12)', { lineHeight: 'var(--text-size-12--line-height)', fontWeight: '400' }],

        // Semantic Typography - Body Semi-Bold
        'body-1-sb': ['var(--text-size-16)', { lineHeight: 'var(--text-size-16--line-height)', fontWeight: '600' }],
        'body-2-sb': ['var(--text-size-15)', { lineHeight: 'var(--text-size-15--line-height)', fontWeight: '600' }],
        'body-3-sb': ['var(--text-size-14)', { lineHeight: 'var(--text-size-14--line-height)', fontWeight: '600' }],
        'body-4-sb': ['var(--text-size-13)', { lineHeight: 'var(--text-size-13--line-height)', fontWeight: '600' }],
        'body-5-sb': ['var(--text-size-12)', { lineHeight: 'var(--text-size-12--line-height)', fontWeight: '600' }],

        // Semantic Typography - Body Bold
        'body-1-b': ['var(--text-size-16)', { lineHeight: 'var(--text-size-16--line-height)', fontWeight: '700' }],
        'body-2-b': ['var(--text-size-15)', { lineHeight: 'var(--text-size-15--line-height)', fontWeight: '700' }],
        'body-3-b': ['var(--text-size-14)', { lineHeight: 'var(--text-size-14--line-height)', fontWeight: '700' }],
        'body-4-b': ['var(--text-size-13)', { lineHeight: 'var(--text-size-13--line-height)', fontWeight: '700' }],
        'body-5-b': ['var(--text-size-12)', { lineHeight: 'var(--text-size-12--line-height)', fontWeight: '700' }],

        // Semantic Typography - Caption (Regular)
        'caption-1': ['var(--text-size-13)', { lineHeight: 'var(--text-size-13--line-height)', fontWeight: '400' }],
        'caption-2': ['var(--text-size-12)', { lineHeight: 'var(--text-size-12--line-height)', fontWeight: '400' }],
        'caption-3': ['var(--text-size-11)', { lineHeight: 'var(--text-size-11--line-height)', fontWeight: '400' }],
      },
      fontWeight: {
        thin: 'var(--font-weight-thin)',
        extralight: 'var(--font-weight-extralight)',
        light: 'var(--font-weight-light)',
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
        extrabold: 'var(--font-weight-extrabold)',
        black: 'var(--font-weight-black)',
      },
      colors: {
        grey: {
          10: 'var(--color-grey-10)',
          20: 'var(--color-grey-20)',
          30: 'var(--color-grey-30)',
          40: 'var(--color-grey-40)',
          50: 'var(--color-grey-50)',
          60: 'var(--color-grey-60)',
          70: 'var(--color-grey-70)',
          80: 'var(--color-grey-80)',
          90: 'var(--color-grey-90)',
          100: 'var(--color-grey-100)',
        },
        navy: {
          20: 'var(--color-navy-20)',
          30: 'var(--color-navy-30)',
          40: 'var(--color-navy-40)',
          50: 'var(--color-navy-50)',
          60: 'var(--color-navy-60)',
          70: 'var(--color-navy-70)',
          80: 'var(--color-navy-80)',
          90: 'var(--color-navy-90)',
          100: 'var(--color-navy-100)',
        },
        blue: {
          20: 'var(--color-blue-20)',
          30: 'var(--color-blue-30)',
          40: 'var(--color-blue-40)',
          50: 'var(--color-blue-50)',
          60: 'var(--color-blue-60)',
          70: 'var(--color-blue-70)',
          80: 'var(--color-blue-80)',
          90: 'var(--color-blue-90)',
          100: 'var(--color-blue-100)',
        },
        green: {
          20: 'var(--color-green-20)',
          30: 'var(--color-green-30)',
          40: 'var(--color-green-40)',
          50: 'var(--color-green-50)',
          60: 'var(--color-green-60)',
          70: 'var(--color-green-70)',
          80: 'var(--color-green-80)',
          90: 'var(--color-green-90)',
          100: 'var(--color-green-100)',
        },
        red: {
          20: 'var(--color-red-20)',
          30: 'var(--color-red-30)',
          40: 'var(--color-red-40)',
          50: 'var(--color-red-50)',
          60: 'var(--color-red-60)',
          70: 'var(--color-red-70)',
          80: 'var(--color-red-80)',
          90: 'var(--color-red-90)',
          100: 'var(--color-red-100)',
        },
        orange: {
          20: 'var(--color-orange-20)',
          30: 'var(--color-orange-30)',
          40: 'var(--color-orange-40)',
          50: 'var(--color-orange-50)',
          60: 'var(--color-orange-60)',
          70: 'var(--color-orange-70)',
          80: 'var(--color-orange-80)',
          90: 'var(--color-orange-90)',
          100: 'var(--color-orange-100)',
        },
        cta: {
          primary: 'var(--color-cta-primary)',
          destructive: 'var(--color-cta-destructive)',
          secondary: 'var(--color-cta-secondary)',
          tertiary: 'var(--color-cta-tertiary)',
        },
        label: {
          1: 'var(--color-label-1)',
          2: 'var(--color-label-2)',
        },
        bg: {
          1: 'var(--color-bg-1)',
          2: 'var(--color-bg-2)',
          3: 'var(--color-bg-3)',
        },
        status: {
          informative: 'var(--color-status-informative)',
          positive: 'var(--color-status-positive)',
          negative: 'var(--color-status-negative)',
          warning: 'var(--color-status-warning)',
        },
      },
      spacing: {
        'space-2': 'var(--space-2)',
        'space-4': 'var(--space-4)',
        'space-6': 'var(--space-6)',
        'space-8': 'var(--space-8)',
        'space-12': 'var(--space-12)',
        'space-16': 'var(--space-16)',
        'space-20': 'var(--space-20)',
        'space-24': 'var(--space-24)',
        'space-28': 'var(--space-28)',
        'space-32': 'var(--space-32)',
        'space-36': 'var(--space-36)',
        'space-40': 'var(--space-40)',
        'space-48': 'var(--space-48)',
        'space-56': 'var(--space-56)',
        'space-64': 'var(--space-64)',
        'space-80': 'var(--space-80)',
        'space-112': 'var(--space-112)',
      },
      boxShadow: {
        small: 'var(--shadow-small)',
        regular: 'var(--shadow-regular)',
        medium: 'var(--shadow-medium)',
        large: 'var(--shadow-large)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--reka-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--reka-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [],
}
